[package]
name = "dvf"
version = "0.1.0"
authors = ["Zico <zhicong303@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miracl_core = {version = "2.7.0", features = ["bls12381"]}
lazy_static = "1.4.0"
num-bigint = {version = "0.4.0", features = ["rand"]}
rand = "0.8.4"
num-traits = "0.2.8"
array-init = "2.0.0"

rayon = "1.4.1"
futures = "0.3.7"
tokio = "1.14.0"
blst = "0.3.3"
eth2_hashing = "0.3.0"

node_test_rig = { path = "lighthouse/testing/node_test_rig" }
#simulator = { path = "lighthouse/testing/simulator" }
parking_lot = "0.12.0"
sensitive_url  = { path = "lighthouse/common/sensitive_url" }
types = { path = "lighthouse/consensus/types" }
lighthouse_bls = { path = "lighthouse/crypto/bls", package="bls"}

[patch]
[patch.crates-io]
fixed-hash = { git = "https://github.com/paritytech/parity-common", rev="df638ab0885293d21d656dc300d39236b69ce57d" }
warp = { git = "https://github.com/macladson/warp", rev="7e75acc368229a46a236a8c991bf251fe7fe50ef" }
eth2_ssz = { path = "lighthouse/consensus/ssz" }
eth2_ssz_derive = { path = "lighthouse/consensus/ssz_derive" }
eth2_ssz_types = { path = "lighthouse/consensus/ssz_types" }
eth2_hashing = { path = "lighthouse/crypto/eth2_hashing" }
tree_hash = { path = "lighthouse/consensus/tree_hash" }
tree_hash_derive = { path = "lighthouse/consensus/tree_hash_derive" }
eth2_serde_utils = { path = "lighthouse/consensus/serde_utils" }


[features]
#default = ["fake_committee"]
fake_committee = []

