version: '3'
services:
  dvf_root_node:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "9005"
    ports:
      - "9005:9005"
  geth:
    build: 
      context: ./geth
      dockerfile: Dockerfile
    expose:
      - "8545"
    ports:
      - "8545:8545"
  lighthouse:
    build: 
      context: ./lighthouse
      dockerfile: Dockerfile
    command: 'lighthouse bn --network ropsten --datadir /var/lib/lighthouse --staking--http-allow-sync-stalled --merge --execution-endpoints http://127.0.0.1:8551 --metrics --validator-monitor-auto --jwt-secrets="/var/lib/goethereum/jwtsecret"  --terminal-total-difficulty-override 50000000000000000 > bn_output 2>&1 &)'
    expose:
      - "5052"
    ports:
      - "5052:5052"
    depends_on:
     - geth
  operator:
    build: 
      context: ./
      dockerfile: Dockerfile-purchaser-api
    expose:
      - "3031"
    ports:
      - "3031:3031"
  ruby-ui:
    stdin_open: true
    tty: true
    build: 
      context: ./Ruby_milestone2
      dockerfile: Dockerfile-ruby-ui
    ports:
      - "3000:3000"
    depends_on:
      - zeropool
      - authority-api
      - owner-api
      - purchaser-api