version: '3'
services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile
    volumes:
      - jwt-data:/data/jwt
      - geth-data:/data/geth
    expose:
      - "8545"
      - "8551"
      - "30303"
    ports:
      - "8545:8545"
      - "8551:8551"
      - "30303:30303"
  lighthouse:
    build: 
      context: ./lighthouse
      dockerfile: Dockerfile
    volumes:
      - geth-data:/data/geth
      - jwt-data:/data/jwt
      - lighthouse-data:/data/lighthouse
    command:
      [
        "lighthouse",
        "bn",
        "--network=ropsten",
        "--datadir=/data/lighthouse",
        "--jwt-secrets=/data/jwt/jwtsecret",
        "--http",
        "--listen-address=0.0.0.0",
        "--http-address=0.0.0.0",
        "--http-port=5052",
        "--staking",
        "--http-allow-sync-stalled",
        "--merge",
        "--execution-endpoints=http://geth:8551",
        "--eth1-endpoints=http://geth:8545",
        "--metrics",
        "--validator-monitor-auto",
        "--terminal-total-difficulty-override=50000000000000000"
      ]
    expose:
      - "5052"
    ports:
      - "5052:5052"
    depends_on:
      geth:
        condition: service_started
  operator:
    volumes:
      - operator-data:/root/.lighthouse
    build:
      context: .
      args:
        CPU_NUM: 16
      dockerfile: Dockerfile
    command: "${ENR}"
    depends_on:
      lighthouse:
        condition: service_started
    
volumes:
  geth-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/geth
  lighthouse-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/lighthouse
  jwt-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/jwt
  operator-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/operator
