version: '3'
services:
  dvf_root_node:
    build: 
      context: .
      args:
        CPU_NUM: 8
      dockerfile: Dockerfile
    command: "boot"
    expose:
      - "9005"
    ports:
      - "9005:9005"