[package]
name = "utils"
version = "0.1.0"
authors = ["zico <zhicong303@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.3.0", features = ["rt", "time", "macros", "sync"] }
log = "0.4.0"
exit-future = "0.2.0"